name: Build test
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'
  push:
    branches:
      - 'fedora-ci'
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'

jobs:
  build-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: s390x
          distro: fedora_latest
          env: |
            COMPILER: gcc
            COMPILER_VERSION: 10
            SANITIZE: no
          run: |
            pwd
            ls -a
            sudo -E .github/workflows/cibuild-setup-fedora.sh
            git config --global --add safe.directory $(pwd)
            .github/workflows/cibuild.sh CONFIGURE MAKE
            sudo -E .github/workflows/cibuild.sh CHECK
            .github/workflows/cibuild.sh INSTALL
